### ISSUE TITLE
用三元运算符来画出“虚线”

### ISSUE THREAD

**Issue by lisangzhou** [lonecapital/lonecapital-chart#1]
1. 可以用三元运算符来画出“虚线”
`plot(e1,"ema20",color=bar_index % 2 == 0 ? color.gray: color.white)`

2. 可以把 `color=#FFC40C` DRY一下

**Comment by chasenio** [comment]
![](https://user-images.githubusercontent.com/13550898/93954116-71caa000-fd7f-11ea-8676-e2ae20d901b8.png)
效果还不错哦

**Comment by u2cc** [comment]
Cool

**Comment by lisangzhou** [comment]
resolved
